name: Create Release Mediatek Filogic
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: "v${{ matrix.tag }} - ${{ matrix.build_env.pkgarch}} :: ${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}} build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['24.10.2']
        build_env:
          - pkgarch: aarch64_cortex-a53
            target: mediatek
            subtarget: filogic
            vermagic: 2ccac7a75355327cb6dfb4df1ecb575e

    steps:
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v${{ matrix.tag }}
          fetch-depth: 0

      - name: Update and install feeds
        run: |
          pkgarch=${{ matrix.build_env.pkgarch }}
          target=${{ matrix.build_env.target }}
          subtarget=${{ matrix.build_env.subtarget }}

          echo "pkgarch: ${pkgarch}, target: ${target}, subtarget: ${subtarget}"

          rm -rf bin/packages/${pkgarch}/awgopenwrt/ || true
          rm -rf bin/targets/${target}/${subtarget}/packages/  || true

          wget https://downloads.openwrt.org/releases/${{ matrix.tag }}/targets/${target}/${subtarget}/feeds.buildinfo -O feeds.conf
          echo "src-git awgopenwrt https://github.com/kozhini/awg-openwrt-customVM" >> ./feeds.conf

          ./scripts/feeds update -a
          ./scripts/feeds install -a

          wget https://downloads.openwrt.org/releases/${{ matrix.tag }}/targets/${target}/${subtarget}/config.buildinfo -O .config
          make defconfig

      - name: Make Kernel Compile with custom vermagic
        run: |
          export FORCE_UNSAFE_CONFIGURE=1
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-proto-amneziawg=y" >> .config

          if [[ $(uname -m) == "aarch64" ]]; then
            echo 'CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/usr/local/go/bin/go"' >> .config
            echo 'CONFIG_GOLANG_BUILD_CACHE_DIR=""' >> .config
          fi

          make defconfig

          echo "=== Stage 1: build tools & toolchain ==="
          make tools/install -i -j$(nproc)
          make toolchain/install -i -j$(nproc)

          echo "=== Stage 2: prepare kernel ==="
          make target/linux/prepare -j$(nproc) V=sc

          echo "=== Force replace vermagic ==="
          VERMAGIC=${{ matrix.build_env.vermagic }}
          echo "Using custom vermagic: $VERMAGIC"
          if grep -q '^LINUX_RELEASE:=' include/kernel-abiversion.mk; then
            sed -i "s/^LINUX_RELEASE:=.*$/LINUX_RELEASE:=$VERMAGIC/" include/kernel-abiversion.mk
          else
            echo "LINUX_RELEASE:=$VERMAGIC" >> include/kernel-abiversion.mk
          fi
          grep LINUX_RELEASE include/kernel-abiversion.mk

          echo "=== Stage 3: compile kernel ==="
          make target/linux/compile -i -j$(nproc) V=sc

      - name: Make ipks amnezia_${{ github.ref_name }}
        run: |
          make -j1 V=sc package/amneziawg-tools/{clean,download,prepare,compile}
          make -j1 V=sc package/kmod-amneziawg/{clean,download,prepare,compile}
          make -j1 V=sc package/luci-proto-amneziawg/{clean,download,prepare,compile}

      - name: Prepare artifacts
        run: |
          tag_name=${{ github.ref_name }}
          mkdir -p awgrelease
          postfix="${tag_name}_v${{ matrix.tag }}_${{ matrix.build_env.pkgarch}}_${{ matrix.build_env.target}}_${{ matrix.build_env.subtarget}}"
          cp bin/packages/${{ matrix.build_env.pkgarch }}/awgopenwrt/amneziawg-tools_*.ipk awgrelease/amneziawg-tools_${postfix}.ipk
          cp bin/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/packages/kmod-amneziawg_*.ipk awgrelease/kmod-amneziawg_${postfix}.ipk
          cp bin/packages/${{ matrix.build_env.pkgarch }}/awgopenwrt/luci-proto-amneziawg_*.ipk awgrelease/luci-proto-amneziawg_${postfix}.ipk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: awgrelease/*.ipk

      - name: Cleanup
        run: |
          rm feeds.conf || true
          rm -rf awgrelease || true
